# Generated by Django 4.1.7 on 2023-03-03 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AquisicoesProdutos',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('data_aquisicao', models.DateTimeField()),
                ('quantidade', models.IntegerField()),
                ('nota_fiscal', models.TextField()),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'aquisicoes_produtos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('telefone', models.CharField(max_length=13)),
            ],
            options={
                'db_table': 'clientes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Distribuidoras',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome_fantasia', models.CharField(max_length=50)),
                ('cnpj', models.CharField(max_length=14, unique=True)),
                ('logradouro', models.CharField(blank=True, max_length=30, null=True)),
                ('numero', models.CharField(max_length=10)),
                ('bairro', models.CharField(max_length=30)),
                ('cidade', models.CharField(max_length=30)),
                ('uf', models.CharField(max_length=2)),
                ('cep', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'distribuidoras',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstoquesFiliais',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('lote', models.CharField(max_length=12)),
                ('data_validade', models.DateTimeField()),
                ('quantidade', models.IntegerField()),
            ],
            options={
                'db_table': 'estoques_filiais',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Filiais',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=30)),
                ('logradouro', models.CharField(max_length=30)),
                ('numero', models.CharField(max_length=10)),
                ('bairro', models.CharField(max_length=30)),
                ('cidade', models.CharField(max_length=30)),
                ('uf', models.CharField(max_length=2)),
                ('cep', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'filiais',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Funcionarios',
            fields=[
                ('matricula', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=180)),
                ('telefone', models.CharField(max_length=13)),
                ('funcao', models.CharField(max_length=20)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('senha', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'funcionarios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricoMovimentacoesEstoques',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('data_movimentacao', models.DateTimeField()),
                ('quantidade_movimentada', models.IntegerField()),
                ('motivo', models.CharField(max_length=15)),
                ('status', models.CharField(max_length=12)),
                ('observacoes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'historico_movimentacoes_estoques',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricoProdutosRestritos',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('observacoes', models.TextField()),
                ('url_documento_retido', models.TextField()),
            ],
            options={
                'db_table': 'historico_produtos_restritos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ItensVendas',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('quantidade', models.IntegerField()),
            ],
            options={
                'db_table': 'itens_vendas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Laboratorios',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('cnpj', models.CharField(max_length=14, unique=True)),
                ('registro_anvisa', models.CharField(max_length=17, unique=True)),
                ('logradouro', models.CharField(max_length=30)),
                ('numero', models.CharField(max_length=10)),
                ('bairro', models.CharField(max_length=30)),
                ('cidade', models.CharField(max_length=30)),
                ('uf', models.CharField(max_length=2)),
                ('cep', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'laboratorios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrdensEntregas',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('data_entrega', models.DateTimeField()),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(max_length=30)),
                ('logradouro', models.CharField(max_length=30)),
                ('numero', models.CharField(max_length=10)),
                ('bairro', models.CharField(max_length=30)),
                ('ponto_referencia', models.CharField(max_length=100)),
                ('cep', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'ordens_entregas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('url_imagem', models.TextField()),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.TextField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('codigo_barras', models.CharField(max_length=13, unique=True)),
            ],
            options={
                'db_table': 'produtos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Servicos',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=30)),
                ('descricao', models.TextField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo_servico', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'servicos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ServicosAdquiridosClientes',
            fields=[
                ('data_aquisicao', models.DateTimeField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'servicos_adquiridos_clientes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VendasProdutos',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('data_compra', models.DateTimeField()),
                ('forma_pagamento', models.CharField(max_length=15)),
                ('porcentagem_desconto', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'vendas_produtos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProdutosMedicamento',
            fields=[
                ('id_produto', models.OneToOneField(db_column='id_produto', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='core.produtos')),
                ('url_bula', models.TextField()),
                ('tipo_medicamento', models.CharField(max_length=20)),
                ('categoria_medicamento', models.CharField(max_length=20)),
                ('classificacao_medicamento', models.CharField(max_length=20)),
                ('retem_receita', models.IntegerField()),
                ('registro_anvisa', models.CharField(max_length=17, unique=True)),
            ],
            options={
                'db_table': 'produtos_medicamento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProdutosNaoMedicamento',
            fields=[
                ('id_produto', models.OneToOneField(db_column='id_produto', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='core.produtos')),
                ('categoria', models.CharField(max_length=30)),
                ('unidade_medida', models.CharField(max_length=10)),
                ('quantidade_medida', models.DecimalField(decimal_places=3, max_digits=8)),
            ],
            options={
                'db_table': 'produtos_nao_medicamento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ServicosFiliais',
            fields=[
                ('id_filial', models.OneToOneField(db_column='id_filial', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='core.filiais')),
            ],
            options={
                'db_table': 'servicos_filiais',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TelefonesDistribuidoras',
            fields=[
                ('id_distribuidora', models.OneToOneField(db_column='id_distribuidora', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='core.distribuidoras')),
                ('telefone', models.CharField(max_length=13)),
            ],
            options={
                'db_table': 'telefones_distribuidoras',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TelefonesFiliais',
            fields=[
                ('id_filial', models.OneToOneField(db_column='id_filial', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='core.filiais')),
                ('telefone', models.CharField(max_length=13)),
            ],
            options={
                'db_table': 'telefones_filiais',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TelefonesLaboratorios',
            fields=[
                ('id_laboratorio', models.OneToOneField(db_column='id_laboratorio', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='core.laboratorios')),
                ('telefone', models.CharField(max_length=13)),
            ],
            options={
                'db_table': 'telefones_laboratorios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FarmaceuticoResponsaveis',
            fields=[
                ('id_medicamento', models.OneToOneField(db_column='id_medicamento', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='core.produtosmedicamento')),
                ('crf', models.CharField(max_length=9)),
                ('uf_registro', models.CharField(max_length=2)),
                ('nome', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'farmaceutico_responsaveis',
                'managed': False,
            },
        ),
    ]
